name: farmingHelper
main: io.github.michaelpeterswa.farmingHelper.farmingHelper
version: 1.3-STABLE
api-version: 1.13
author: nwradio
commands:
  fh:
    description: This is the main farmingHelper command
    usage: /fh
    permission: farmingHelper.fh
    permission-message: You don't have permission to use FarmingHelper

permissions:
  farmingHelper.*:
    description: Gives access to all farming commands
    children:
      farmingHelper.fh.hoe: true
      farmingHelper.fh.hoe.others: true
  farmingHelper.fh.hoe:
    description: Allows you to give yourself a hoe
    default: true
  farmingHelper.fh.hoe.others:
    description: Allows you to give others a hoe (as op)
    default: op
    children:
      farmingHelper.fh.hoe: true